name: PdfParser
channels:
  - conda-forge
dependencies:
  - python=3.9
  - black
  - flake8
  - isort
  - pip
  - pre-commit
  - commitizen
  - dill
  - pip:
    - PyMuPDF
    - python-dotenv
    - fitz
    - prepCV
    - opencv-python
    - paddleocr
    - paddlepaddle
    - tensorflow
